import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'

export default [
    {
        ignores: ['dist', 'dist-electron']
    },
    ...tseslint.configs.recommended,
    {
        files: ['**/*.{ts,tsx}'],
        languageOptions: {
            ecmaVersion: 2020,
            globals: {
                ...globals.browser,
                ...globals.node,
            },
            parserOptions: {
                project: ['./tsconfig.json', './tsconfig.node.json'],
                tsconfigRootDir: import.meta.dirname,
            },
        },
        plugins: {
            'react-hooks': reactHooks,
            'react-refresh': reactRefresh,
        },
        rules: {
            ...reactHooks.configs.recommended.rules,
            'react-refresh/only-export-components': [
                'warn',
                { allowConstantExport: true },
            ],
            // Possible Errors
            'comma-dangle': ['error', {
                'arrays': 'always',
                'objects': 'always',
                'imports': 'never',
                'exports': 'never',
                'functions': 'never'
            }],
            'no-cond-assign': 'error',
            'no-console': 'off',
            'no-constant-condition': 'error',
            'no-control-regex': 'error',
            'no-debugger': 'error',
            'no-dupe-args': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-empty-character-class': 'error',
            'no-empty': ['error', { 'allowEmptyCatch': true }],
            'no-ex-assign': 'error',
            'no-extra-boolean-cast': 'error',
            'no-extra-parens': ['error', 'all', {
                'nestedBinaryExpressions': false
            }],
            'no-extra-semi': 'error',
            'no-func-assign': 'error',
            'no-inner-declarations': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-negated-in-lhs': 'error',
            'no-obj-calls': 'error',
            'no-regex-spaces': 'error',
            'no-sparse-arrays': 'error',
            'no-unexpected-multiline': 'error',
            'no-unreachable': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',

            // Best Practices
            'accessor-pairs': 'error',
            'block-scoped-var': 'error',
            'complexity': ['error', { 'max': 20 }],
            'consistent-return': 'off',
            'curly': 'error',
            'default-case': 'error',
            'dot-location': ['error', 'property'],
            'dot-notation': 'error',
            'eqeqeq': 'error',
            'guard-for-in': 'error',
            'no-alert': 'error',
            'no-caller': 'error',
            'no-case-declarations': 'error',
            'no-div-regex': 'error',
            'no-else-return': 'warn',
            'no-empty-pattern': 'error',
            'no-eq-null': 'error',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-fallthrough': 'error',
            'no-floating-decimal': 'error',
            '@typescript-eslint/no-floating-promises': 'error',
            'no-implicit-coercion': 'off',
            'no-implied-eval': 'error',
            'no-invalid-this': 'off',
            'no-iterator': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-loop-func': 'error',
            'no-magic-numbers': 'off',
            '@typescript-eslint/no-magic-numbers': ['error', {
                'ignore': [0, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 64, 1000, 3000, 5000, 8000, 9000, 30000, 240000, 200, 201, 204, 400, 404],
                'ignoreArrayIndexes': true,
                'ignoreReadonlyClassProperties': true
            }],
            '@typescript-eslint/no-misused-promises': 'error',
            'no-multi-spaces': 'error',
            'no-multi-str': 'off',
            'no-native-reassign': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-new': 'off',
            'no-octal-escape': 'error',
            'no-octal': 'error',
            'no-param-reassign': 'error',
            'no-process-env': 'off',
            'no-proto': 'error',
            'no-redeclare': 'error',
            'no-return-assign': 'error',
            'no-script-url': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-throw-literal': 'error',
            'no-unused-expressions': ['error', { 'allowShortCircuit': true }],
            'no-useless-call': 'error',
            'no-useless-concat': 'error',
            'no-void': 'error',
            'no-warning-comments': 'off',
            'no-with': 'error',
            'radix': 'error',
            'vars-on-top': 'warn', // Should be enabled at some point
            'wrap-iife': ['error', 'inside'],
            'yoda': ['error', 'never', { 'exceptRange': true }],

            // Strict Mode
            'strict': ['off', 'global'],

            // Variables
            'init-declarations': 'off',
            'no-catch-shadow': 'error',
            'no-delete-var': 'error',
            'no-label-var': 'error',
            'no-shadow-restricted-names': 'error',
            'no-shadow': 'error',
            'no-undef-init': 'error',
            'no-undef': 'error',
            'no-undefined': 'off',
            'no-unused-vars': 'off',
            '@typescript-eslint/no-unused-vars': 'warn',
            'no-use-before-define': 'error',

            // Stylistic Issues
            'array-bracket-spacing': ['error', 'never'],
            'block-spacing': 'error',
            'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
            'camelcase': 'off',
            'comma-spacing': ['error', { 'before': false, 'after': true }],
            'comma-style': ['error', 'last'],
            'computed-property-spacing': ['error', 'never'],
            'consistent-this': ['error', 'that'],
            'eol-last': 'error',
            'func-names': 'off',
            'func-style': 'off',
            'id-length': 'off',
            'id-match': 'off',
            'indent': ['error', 4, { 'SwitchCase': 1 }],
            'jsx-quotes': 'off',
            'key-spacing': ['error', { 'beforeColon': false, 'afterColon': true }],
            'linebreak-style': ['error', 'unix'],
            'lines-around-comment': 'off',
            'max-nested-callbacks': ['error', 5],
            'new-cap': 'error',
            'new-parens': 'error',
            'newline-after-var': 'error',
            'no-array-constructor': 'error',
            'no-continue': 'error',
            'no-inline-comments': 'off',
            'no-lonely-if': 'error',
            'no-mixed-spaces-and-tabs': 'error',
            'no-multiple-empty-lines': ['error', { 'max': 2 }],
            'no-negated-condition': 'error',
            'no-nested-ternary': 'error',
            'no-new-object': 'error',
            'no-restricted-syntax': 'off',
            'no-spaced-func': 'off',
            'no-ternary': 'off',
            'no-trailing-spaces': 'error',
            'no-underscore-dangle': 'off',
            'no-unneeded-ternary': 'error',
            'object-curly-spacing': ['error', 'always', {
                'objectsInObjects': true,
                'arraysInObjects': true
            }],
            'one-var': ['error', 'never'],
            'operator-assignment': 'error',
            'operator-linebreak': ['error', 'after'],
            'padded-blocks': 'off',
            'quote-props': ['error', 'consistent-as-needed'],
            'quotes': ['error', 'single', 'avoid-escape'],
            'semi-spacing': ['error', { 'before': false, 'after': true }],
            'semi': ['error', 'always'],
            'sort-vars': 'off',
            'keyword-spacing': 'error',
            'space-before-blocks': 'error',
            'space-before-function-paren': ['error', {
                'anonymous': 'always',
                'named': 'always'
            }],
            'space-in-parens': ['error', 'never'],
            'space-infix-ops': 'error',
            'space-unary-ops': 'error',
            'spaced-comment': ['error', 'always', {
                'exceptions': ['-', '+', '!']
            }],
            'wrap-regex': 'error',

            // ES6
            'arrow-parens': ['error', 'always'],

            // Legacy
            'max-depth': ['error', 4],
            'max-len': ['error', 120],
            'max-params': ['error', 5],
            'max-statements': 'off',
            'no-bitwise': 'error',
            'no-plusplus': 'off'
        },
    },
]
